"""Remove description from ShareSettings

Revision ID: 69b0b2bffc1f
Revises: 40ed71c2fd01
Create Date: 2025-05-13 03:05:39.009826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69b0b2bffc1f'
down_revision = '40ed71c2fd01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_settings', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('transaction_type')
        batch_op.drop_column('amount')
        batch_op.drop_column('balance')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=256), nullable=False))
        batch_op.add_column(sa.Column('balance', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('amount', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('transaction_type', sa.VARCHAR(length=32), nullable=True))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=64), nullable=True))

    # ### end Alembic commands ###
