"""Added new column

Revision ID: cd2acebf33e9
Revises: 
Create Date: 2025-05-04 18:19:05.853314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd2acebf33e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions_form', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
