"""renamed column to category

Revision ID: dd7b6a25c8e6
Revises: cd2acebf33e9
Create Date: 2025-05-04 19:15:09.554302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd7b6a25c8e6'
down_revision = 'cd2acebf33e9'
branch_labels = None
depends_on = None


def upgrade():
    op.execute('UPDATE transactions_form SET category = transaction_detail')

    # ✅ Then drop transaction_detail
    with op.batch_alter_table('transactions_form', schema=None) as batch_op:
        batch_op.drop_column('transaction_detail')



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_detail', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
